# Generated by Django 5.1.4 on 2026-09-08 12:31

import django.db.models.deletion
import tours.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('code', models.CharField(blank=True, help_text='Short key, e.g. SAFARI', max_length=40)),
                ('short_description', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', validators=[tours.validators.validate_image])),
                ('video', models.FileField(blank=True, null=True, upload_to='categories/video/', validators=[tours.validators.validate_video])),
                ('order', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=True, help_text='Show in the main navigation')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('region', models.CharField(choices=[('northern', 'Northern Circuit'), ('southern', 'Southern Circuit'), ('western', 'Western Tanzania'), ('coastal', 'Coast & Islands'), ('zanzibar', 'Zanzibar'), ('mountain', 'Mountains & Highlands'), ('other', 'Other')], default='other', max_length=20)),
                ('aliases', models.TextField(blank=True, help_text="Other spellings the client uses, one per line. Used when importing content so 'Serengeti' and 'Serengeti National Park' stay one place.")),
                ('short_description', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(blank=True, help_text='Image URL, or upload a file below')),
                ('image_upload', models.ImageField(blank=True, null=True, upload_to='destinations/', validators=[tours.validators.validate_image])),
                ('video', models.FileField(blank=True, help_text='Optional background clip (mp4/webm), muted and short.', null=True, upload_to='destinations/video/', validators=[tours.validators.validate_video])),
                ('order', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, max_length=120)),
                ('headline', models.CharField(max_length=160)),
                ('headline_script', models.CharField(blank=True, help_text="Short second line set in the script face, e.g. 'up close'", max_length=80)),
                ('subline', models.CharField(blank=True, max_length=250)),
                ('image', models.ImageField(blank=True, help_text='Still background; also the poster frame for the video.', null=True, upload_to='hero/', validators=[tours.validators.validate_image])),
                ('video', models.FileField(blank=True, help_text='Muted looping clip. The image is used instead on mobile.', null=True, upload_to='hero/video/', validators=[tours.validators.validate_video])),
                ('cta_label', models.CharField(blank=True, max_length=60)),
                ('cta_url', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/', validators=[tours.validators.validate_image])),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TransferService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Lucide icon name, e.g. 'plane'", max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='transfers/', validators=[tours.validators.validate_image])),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='tours.category')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text='Leave blank for activities priced by the hour.', null=True)),
                ('duration_nights', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_text', models.CharField(blank=True, help_text="Shown when there is no whole-day figure, e.g. '2–3 hours', 'Half day'.", max_length=60)),
                ('starting_point', models.CharField(blank=True, max_length=200)),
                ('route', models.CharField(blank=True, help_text="Climbing route, e.g. 'Machame Route'", max_length=120)),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('price_basis', models.CharField(choices=[('person', 'per person'), ('couple', 'per couple'), ('adult', 'per adult'), ('group', 'per group'), ('boat', 'per private boat'), ('vehicle', 'per vehicle')], default='person', help_text='A couple package priced per couple must NOT display as per person.', max_length=12)),
                ('short_description', models.CharField(blank=True, max_length=400)),
                ('description', models.TextField(blank=True)),
                ('highlights', models.TextField(blank=True, help_text='One per line')),
                ('includes', models.TextField(blank=True, help_text='One per line')),
                ('excludes', models.TextField(blank=True, help_text='One per line')),
                ('best_for', models.TextField(blank=True)),
                ('important_note', models.TextField(blank=True, help_text='Caveats — wildlife sightings, weather, permits.')),
                ('image', models.URLField(blank=True)),
                ('image_upload', models.ImageField(blank=True, null=True, upload_to='packages/', validators=[tours.validators.validate_image])),
                ('video', models.FileField(blank=True, null=True, upload_to='packages/video/', validators=[tours.validators.validate_video])),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True, help_text='Untick to hide a package that is missing content.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(related_name='packages', to='tours.category')),
                ('destinations', models.ManyToManyField(blank=True, related_name='packages', to='tours.destination')),
                ('primary_category', models.ForeignKey(help_text='Used for the breadcrumb and the canonical URL.', on_delete=django.db.models.deletion.PROTECT, related_name='primary_packages', to='tours.category')),
            ],
            options={
                'ordering': ['order', 'duration_days', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('package_interest', models.CharField(blank=True, max_length=200)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('adults', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('children', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled', models.BooleanField(default=False)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='tours.package')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='packages/gallery/', validators=[tours.validators.validate_image])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='tours.package')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=120)),
                ('author_country', models.CharField(blank=True, max_length=100)),
                ('quote', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='tours.package')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='tours.package')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('package', 'day_number')},
            },
        ),
    ]
