# Generated by Django 5.1.4 on 2026-09-08 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Decimal degrees, negative south of the equator. Used to place this destination on the routes map.', null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Decimal degrees.', null=True),
        ),
        migrations.CreateModel(
            name='MapRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('colour', models.CharField(default='#B98431', help_text='Hex colour for the line and its legend swatch, e.g. #B98431', max_length=7)),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(blank=True, help_text='Optional — links the legend entry through to a bookable tour.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_routes', to='tours.package')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='tours.destination')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='tours.maproute')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('route', 'destination', 'order')},
            },
        ),
    ]
