# Generated by Django 5.1.4 on 2026-09-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_destination_latitude_destination_longitude_maproute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bead_colour',
            field=models.CharField(default='#B98431', help_text="Hex colour of this category's bead in the navigation menu.", max_length=7),
        ),
    ]
