# Generated by Django 5.1.4 on 2026-09-10 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_category_bead_colour'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('mountain', models.CharField(default='Mount Kilimanjaro', max_length=80)),
                ('summary', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='bead_colour',
            field=models.CharField(default='#B5813F', help_text='Hex colour marking this category in the menu and on cards.', max_length=7),
        ),
        migrations.AlterField(
            model_name='maproute',
            name='colour',
            field=models.CharField(default='#B5813F', help_text='Hex colour for the line and its legend swatch, e.g. #C2662B', max_length=7),
        ),
        migrations.AddField(
            model_name='package',
            name='climb_route',
            field=models.ForeignKey(blank=True, help_text="Draws the altitude profile on this tour's page.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='tours.climbroute'),
        ),
        migrations.CreateModel(
            name='ClimbStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('altitude_m', models.PositiveIntegerField(help_text='Metres above sea level')),
                ('day', models.PositiveIntegerField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='tours.climbroute')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
