# Generated by Django 5.1.4 on 2026-09-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_category_bead_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='bead_colour',
            field=models.CharField(default='#B5813F', help_text='Hex colour marking this category in the menu and on cards.', max_length=7),
        ),
        migrations.AlterField(
            model_name='maproute',
            name='colour',
            field=models.CharField(default='#B5813F', help_text='Hex colour for the line and its legend swatch, e.g. #C2662B', max_length=7),
        ),
    ]
