# Generated by Django 5.1.4 on 2026-09-10 08:59

import django.db.models.deletion
import tours.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_climbroute_alter_category_bead_colour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('board_basis', models.CharField(blank=True, help_text="e.g. 'Bed & breakfast'. Shown next to the rate.", max_length=60)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stay/', validators=[tours.validators.validate_image])),
                ('video', models.FileField(blank=True, null=True, upload_to='stay/video/', validators=[tours.validators.validate_video])),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'accommodation',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='transferservice',
            name='currency',
            field=models.CharField(default='USD', max_length=8),
        ),
        migrations.AddField(
            model_name='transferservice',
            name='distance_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferservice',
            name='duration_text',
            field=models.CharField(blank=True, help_text="e.g. '9-15 minutes'", max_length=60),
        ),
        migrations.AddField(
            model_name='transferservice',
            name='price_basis',
            field=models.CharField(choices=[('trip', 'per trip'), ('day', 'per day'), ('person', 'per person'), ('cup', 'per cup')], default='trip', max_length=10),
        ),
        migrations.AddField(
            model_name='transferservice',
            name='price_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='transferservice',
            name='price_to',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fill in only when the price is a range.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='transferservice',
            name='route_from',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='transferservice',
            name='route_to',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='AccommodationFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('detail', models.CharField(blank=True, max_length=250)),
                ('order', models.PositiveIntegerField(default=0)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='tours.accommodation')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AccommodationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stay/gallery/', validators=[tours.validators.validate_image])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='tours.accommodation')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
