# Generated by Django 5.1.4 on 2026-09-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_accommodation_transferservice_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text="What the photo shows, for screen readers and search engines. 'Guests having coffee on the veranda', not 'IMG_4821'.", max_length=200),
        ),
        migrations.AlterField(
            model_name='accommodationimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Shown under the photo. Optional.', max_length=200),
        ),
    ]
