# Generated by Django 5.1.4 on 2026-09-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_category_bead_colour_alter_maproute_colour'),
        ('tours', '0006_accommodationimage_alt_text_and_more'),
    ]

    operations = [
    ]
