# Generated by Django 5.1.4 on 2026-09-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_merge_20260912_1839'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['published', 'featured'], name='pkg_pub_feat_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['published', 'duration_days'], name='pkg_pub_days_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['order', 'duration_days', 'title'], name='pkg_order_idx'),
        ),
    ]
