# Generated by Django 5.1.4 on 2026-09-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_package_pkg_pub_feat_idx_package_pkg_pub_days_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbstage',
            name='coords_verified',
            field=models.BooleanField(default=False, help_text="Tick once a guide who has walked this camp has confirmed the position. While any camp on a route is unticked, the map carries a 'positions approximate' note."),
        ),
        migrations.AddField(
            model_name='climbstage',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Decimal degrees, negative south of the equator. Leave blank and this camp is left off the map rather than guessed at.', null=True),
        ),
        migrations.AddField(
            model_name='climbstage',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Decimal degrees.', null=True),
        ),
    ]
