"""Generate the beadwork motifs as standalone SVG files and as CSS data URIs."""
import urllib.parse, pathlib

BEADS = ["#B23A2E", "#F2EADA", "#2B5DA8", "#DE8B24", "#2E7D4F", "#17140F"]

def shuka(size=64):
    """
    The checked weave of a Maasai shuka, reduced to a two-colour grid at very
    low contrast. It is a texture, not a pattern you are meant to notice — it
    keeps the dark green panels from reading as flat printed bars.
    """
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{size}" height="{size}" '
        f'viewBox="0 0 {size} {size}">'
        f'<path d="M0,{size*0.5} H{size} M{size*0.5},0 V{size}" '
        f'stroke="#FFFFFF" stroke-width="1" opacity="0.05"/>'
        f'<path d="M0,{size*0.25} H{size} M{size*0.75},0 V{size}" '
        f'stroke="#FFFFFF" stroke-width="0.6" opacity="0.03"/>'
        '</svg>'
    )


def datauri(svg):
    return "url(\"data:image/svg+xml,%s\")" % urllib.parse.quote(svg, safe="")


out = pathlib.Path("static/img")
out.mkdir(parents=True, exist_ok=True)
(out / "shuka.svg").write_text(shuka())

css = [
    "/* Generated by scripts/gen_motifs.py - edit there, not here. */",
    ":root {",
    f"  --shuka: {datauri(shuka())};",
    "}",
]
pathlib.Path("static/css/motifs.css").write_text("\n".join(css) + "\n")
print("shuka.svg + motifs.css written")
