"""
Find a tour's slug.

    python manage.py find_package materuni
    python manage.py find_package coffee --day-trips
    python manage.py find_package ""            (lists everything)

Slugs are generated by import_packages from the tour titles, so they differ
between one import and the next and between one database and another. Copying
a slug out of a document — or out of somebody else's database — is how you get
"No package with slug ...". Look it up here instead.
"""

from django.core.management.base import BaseCommand

from tours.models import Package


class Command(BaseCommand):
    help = "Search tours by keyword and print their slugs."

    def add_arguments(self, parser):
        parser.add_argument("keyword", nargs="?", default="",
                            help="Part of the title. Leave blank to list all.")
        parser.add_argument("--day-trips", action="store_true",
                            help="Only single-day tours.")
        parser.add_argument("--unpublished", action="store_true",
                            help="Only tours that are not live yet.")

    def handle(self, *args, **options):
        qs = Package.objects.all()
        if options["keyword"]:
            qs = qs.filter(title__icontains=options["keyword"])
        if options["day_trips"]:
            qs = qs.filter(duration_days=1)
        if options["unpublished"]:
            qs = qs.filter(published=False)
        qs = qs.order_by("duration_days", "title")

        if not qs:
            self.stdout.write(self.style.WARNING("Nothing matched."))
            return

        self.stdout.write("")
        for p in qs:
            days = f"{p.duration_days}d" if p.duration_days else "--"
            price = f"${p.price_from:.0f}" if p.price_from else "no price"
            live = "  " if p.published else " UNPUBLISHED"
            self.stdout.write(f"  {days:>4}  {price:>9}{live}  {p.slug}")
            self.stdout.write(f"        {p.title}")
        self.stdout.write(f"\n{qs.count()} tour(s).")
